from Katana import NodegraphAPI
from Katana import KatanaFile
#import json

#can be populated using yaml or json generated by modeling.
partList = ["body","rgt_hand","lft_hand","rgt_leg","lft_leg","head","eyes"]

gsMTL = NodegraphAPI.CreateNode("GroupStack", NodegraphAPI.GetRootNode())

gsMTL.setName("MaterialStack")
gsMTL.setChildNodeType('Material')

childNodeList = []

for part in partList:
    mtlChild = gsMTL.buildChildNode()
    mtlChild.getParameter('name').setValue("MTL_"+part,0)
    childNodeList.append(mtlChild)
